import type { AutomationStep } from './automationTypes';

/**
 * Generates an idiomatic Playwright TypeScript test script (.spec.ts)
 * from recorded/configured Chrome Lite automation steps.
 */
export function generateLocalPlaywrightScript(flowName: string, steps: AutomationStep[]): string {
  const safeName = (flowName || 'Chrome Automation Flow').replace(/'/g, "\\'");
  let script = `import { test, expect } from '@playwright/test';\n\n`;
  script += `/**\n * Generated by Chrome Lite Automation Engine\n * Flow: ${safeName}\n * Total Steps: ${steps.length}\n */\n`;
  script += `test('${safeName}', async ({ page }) => {\n`;

  for (let i = 0; i < steps.length; i++) {
    const s = steps[i];
    script += `  // Step ${i + 1}: ${s.type}\n`;
    switch (s.type) {
      case 'navigate':
        script += `  await page.goto('${s.url || 'https://google.com'}', { waitUntil: 'domcontentloaded' });\n`;
        break;
      case 'click':
        script += `  await page.locator('${s.selector || 'body'}').first().click();\n`;
        break;
      case 'type':
        script += `  await page.locator('${s.selector || 'input'}').first().fill('${(s.value || '').replace(/'/g, "\\'")}');\n`;
        break;
      case 'wait':
        script += `  await page.waitForTimeout(${s.ms || 1000});\n`;
        break;
      case 'scroll':
        if (s.selector) {
          script += `  await page.locator('${s.selector}').first().scrollIntoViewIfNeeded();\n`;
        } else {
          script += `  await page.evaluate(() => window.scrollBy(0, ${s.y || 600}));\n`;
        }
        break;
      case 'screenshot':
        script += `  await page.screenshot({ path: 'screenshot-${i + 1}.png', fullPage: false });\n`;
        break;
      case 'extract':
        script += `  const extracted_${i + 1} = await page.locator('${s.selector || 'body'}').allInnerTexts();\n`;
        script += `  console.log('Extracted step ${i + 1}:', extracted_${i + 1});\n`;
        break;
      case 'if_element_exists':
        script += `  if (await page.locator('${s.selector}').count() > 0) {\n`;
        if (s.thenAction === 'click') {
          script += `    await page.locator('${s.thenSelector || s.selector}').first().click();\n`;
        } else if (s.thenAction === 'wait') {
          script += `    await page.waitForTimeout(1000);\n`;
        } else if (s.thenAction === 'extract') {
          script += `    const condItems = await page.locator('${s.thenSelector || s.selector}').allInnerTexts();\n`;
          script += `    console.log('Condition met, extracted:', condItems);\n`;
        } else {
          script += `    await page.evaluate(() => window.scrollBy(0, 400));\n`;
        }
        script += `  }\n`;
        break;
      case 'if_text_contains':
        script += `  const pageContent_${i + 1} = await page.locator('${s.selector || 'body'}').innerText();\n`;
        script += `  if (pageContent_${i + 1}.toLowerCase().includes('${(s.text || '').toLowerCase().replace(/'/g, "\\'")}')) {\n`;
        if (s.thenAction === 'click' && s.thenSelector) {
          script += `    await page.locator('${s.thenSelector}').first().click();\n`;
        } else {
          script += `    console.log('Target text found on page');\n`;
        }
        script += `  }\n`;
        break;
      case 'loop_elements':
        script += `  const elements_${i + 1} = page.locator('${s.selector}');\n`;
        script += `  const count_${i + 1} = Math.min(await elements_${i + 1}.count(), ${s.maxIterations || 5});\n`;
        script += `  for (let idx = 0; idx < count_${i + 1}; idx++) {\n`;
        script += `    const item = elements_${i + 1}.nth(idx);\n`;
        script += `    await item.scrollIntoViewIfNeeded();\n`;
        if (s.loopAction === 'click') {
          script += `    await item.click();\n`;
        } else if (s.loopAction === 'extract') {
          script += `    console.log('Item ' + idx + ':', await item.innerText());\n`;
        }
        script += `    await page.waitForTimeout(300);\n`;
        script += `  }\n`;
        break;
    }
    script += `\n`;
  }

  script += `});\n`;
  return script;
}
